{% set version = "0.1" %}
{% set name = "dna-nn" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/lh3/dna-nn/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bac26a25ad9e0315351b170bc33ab4e41b7573818fd9527b661f882b96ae0a8a

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("dna-nn", max_pin="x.x") }}

requirements:
    build:
      - make
      - {{ compiler('cxx') }}
      - zlib  # zlib needed in build to build correctly
    host:
      - zlib      
    run:      
      - k8

test:
  commands:
    - dna-brnn 2>&1 | grep "Usage: dna-brnn" #-Ai attcc-alpha.knm -t16 test.fa > seq.bed
    - dna-cnn 2>&1 | grep "Usage: dna-cnn"
    - gen-fq 2>&1 | grep "Usage: gen-fq"
    - parse-rm.js 2>&1 | grep "Usage: k8 parse-rm"

about:
  home: "https://github.com/lh3/dna-nn"
  dev_url: "https://github.com/lh3/dna-nn"
  license: Unknown
  summary: "Model and predict short DNA sequence features with neural networks."

extra:
  recipe-maintainers:
      - smeds
